server:
  port: 8081
logging:
  level:
    root: INFO
  config: "classpath:logback.xml"

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    h2:
      console:
        enabled: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baseline-on-migrate: false


buduj: true

dane:
    wejsciowe:
      1: Jarek Z

support:
      applicationName: Abc
      email: jarekpc@o2.pl

